server:
  port: 8083
spring:
  application:
    name: manage-servcie
  cloud:
    zookeeper:
      connect-string: 192.168.11.132:2181
      discovery:
        enabled: true
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  rabbitmq:
    host: 192.168.11.132
    port: 5672
    username: admin
    password: admin

mybatis-plus:
  type-aliases-package: com.cy.pojo #持久层的数据对象包名路径
  mapper-locations: classpath:/mybatis/mappers/*.xml #识别sql的xml文件
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则
logging:
  level:
    com.cy.mapper: debug #记录日志 记录持久层的行为

dubbo:
  scan:
    basePackages: com.cy
  application:
    name: provider-manage
  registry:
    address: zookeeper://192.168.11.131:2181?backup=192.168.11.131:2182,192.168.11.131:2183
  protocol:
    name: dubbo
    port: 20882

#开启异步线程配置 不使用呢tomcat线程 提高系统性能
async-thread-pool:
  corePoolSize: 20
  maxPoolSize: 1000
  keepAliveSeconds: 30
  queueCapacity: 1000

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh