spring:
  application:
    name: web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  rabbitmq:
    host: 192.168.11.132
    port: 5672
    username: admin
    password: admin
server:
  port: 8080

dubbo:
  scan:
    basePackages: com.cy
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.11.131:2181?backup=192.168.11.131:2182,192.168.11.131:2183

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

